server:
  port: 8801

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#zuul:
#  routes:
#    api-hello:
#      path: /api/helloservice/**
#      serviceId: hello-service
#    api-time:
#      path: /api/timeservice/**
#      serviceId: time-service